# Cross-Agent Memory Intelligence System Orchestrator Configuration

startup_sequence:
  - service: "docker"
    wait_seconds: 5
    description: "Start PostgreSQL and Qdrant vector database"
  - service: "langflow"
    wait_seconds: 10
    description: "Start LangFlow server for memory workflows"
  - service: "memory_graph_api"
    wait_seconds: 3
    description: "Start memory graph relationship service"
  - service: "temporal_processor"
    wait_seconds: 3
    description: "Start temporal intelligence engine"
  - service: "audit_system"
    wait_seconds: 2
    description: "Initialize security audit system"
  - service: "raycast_sync"
    wait_seconds: 2
    description: "Sync configurations to Raycast"

# Health monitoring configuration
health_check_interval: 30  # seconds
auto_restart: true
restart_max_attempts: 3
restart_delay_seconds: 10

# Default resource profile
resource_profile: "balanced"

# Service configurations
services:
  docker:
    enabled: true
    compose_file: "/Users/josephhillin/workspace/mcp-central/docker-compose.yaml"
    profile: "balanced"
    timeout_seconds: 60
    health_check_url: "http://localhost:5432"
    
  langflow:
    enabled: true
    host: "localhost"
    port: 7860
    auto_deploy_flows: true
    health_check_url: "http://localhost:7860/health"
    timeout_seconds: 120
    flows_directory: "/Users/josephhillin/workspace/mcp-central/agents"
    
  memory_graph_api:
    enabled: true
    port: 8767
    script: "/Users/josephhillin/workspace/mcp-central/graph/memory-graph-service.py"
    health_check_url: "http://localhost:8767/health"
    timeout_seconds: 30
    
  temporal_processor:
    enabled: true
    schedule: "*/5 * * * *"  # Every 5 minutes
    script: "/Users/josephhillin/workspace/mcp-central/agents/temporal-engine/temporal-processor.py"
    daemon_mode: true
    
  audit_system:
    enabled: true
    log_level: "INFO"
    log_file: "/Users/josephhillin/workspace/mcp-central/security/audit.log"
    retention_days: 90
    
  raycast_sync:
    enabled: true
    auto_discover: true
    sync_interval_minutes: 60

# Logging configuration
logging:
  level: "INFO"
  file: "/Users/josephhillin/workspace/mcp-central/orchestrator.log"
  max_size_mb: 100
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance monitoring
monitoring:
  cpu_threshold_percent: 80
  memory_threshold_percent: 85
  disk_threshold_percent: 90
  network_timeout_seconds: 30
  
# Security settings
security:
  enable_audit_trail: true
  log_all_operations: true
  suspicious_activity_detection: true
  max_failed_attempts: 5
  lockout_duration_minutes: 15

# Team collaboration settings
team_mode:
  enabled: true
  default_sharing_scope: "team"
  require_approval_for_sharing: false
  max_team_size: 50

# Integration settings
integrations:
  raycast:
    enabled: true
    config_directory: "/Users/josephhillin/.config/raycast"
    auto_sync: true
    
  mcp_servers:
    enabled: true
    config_file: "/Users/josephhillin/mcp/mcp_server_config.json"
    auto_discover: true
    
  openmemory:
    enabled: true
    api_endpoint: "http://localhost:8765"
    vector_db_endpoint: "http://localhost:6333"
    
  langflow_bridge:
    enabled: true
    bridge_port: 8768
    mcp_compatibility: true

# Backup and recovery
backup:
  enabled: true
  interval_hours: 24
  retention_days: 30
  backup_directory: "/Users/josephhillin/workspace/mcp-central/backups"
  include_databases: true
  include_configs: true
  
# Development and testing
development:
  test_mode: false
  mock_external_services: false
  integration_tests_on_startup: false
  debug_mode: false
